### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Seoman7**
Update of Communities in Nordhessen

### CODE REVIEW

**Comment by herbetom** [comment]
So far, each listed city stands for its own community and cities that are co-supplied are not listed individually. I think it is not the correct approach to simply list a larger number of seemingly stand-alone cities, but always link to the same destination.
Maybe one Box would be enough?

It would be nice if you could change the title of the PR to something a little bit more meaningful.

**Comment by Seoman7** [comment]
Hmm, but our Setup is one Club with different local sites/ communities/ local contact persons, which are using the same multidomain firmware. Shouldn't the list show the visitors the places where freifunk is organised and present to the public? At the moment we drive 6 communities in 6 cities but have nodes in over 20 cities in the region. and we just started to grow.
If I would be new to freifunk, I'd like to know if there is a local contact in my city to get access to freifunk and to have to talk to someone I know. And not need to talk to someone who is 200km away in a village I didn't know.:-)

**Comment by blocktrron** [comment]
> f I would be new to freifunk, I'd like to know if there is a local contact in my city to get access to freifunk and to have to talk to someone I know. And not need to talk to someone who is 200km away in a village I didn't know.:-)

You are creating multiple links to the same page, so I assume a list of contacts is maintained there? So why not go with Nordhessen, so new potential "ambassadors" in Cities without an active Community can find their correct metacommunity.

TBH. I'd like to have a map where someone can just click on their region and get to the nearest community, but that's a classic "PR welcome".

**Comment by Seoman7** [comment]
> > f I would be new to freifunk, I'd like to know if there is a local contact in my city to get access to freifunk and to have to talk to someone I know. And not need to talk to someone who is 200km away in a village I didn't know.:-)
> 
> You are creating multiple links to the same page, so I assume a list of contacts is maintained there? So why not go with Nordhessen, so new potential "ambassadors" in Cities without an active Community can find their correct metacommunity.
> 
> TBH. I'd like to have a map where someone can just click on their region and get to the nearest community, but that's a classic "PR welcome".

Hmm, the problem is, that Nordhessen is really quite big... with different regions. And yes you are right, that the link is a list of Contacts n the different regions or "verticals" like publics . And we'ld like to have our cities in the list, so that the people see, where Freifunk is still availible today, and where they can get in touch with local guys..

**Comment by mweinelt** [comment]
I'm not happy either, but not listing Nordhessen is also not an option. I'm going to merge now, and if we have a plan to improve this (like a map … maybe) we can improve on this.

**Comment by mweinelt** [comment]
The maps here use GeoJSON fences, that feels like the way to go:
- https://downloader.freifunk-siegburg.de/
- https://darmstadt.freifunk.net/mitmachen/domains/

**Pull request merged**
